### ISSUE TITLE
Correct Current setting

### ISSUE THREAD

**Issue by axjurado** [kliment/cooldrv#1]
Can you please verify whether the current is set by Vref/2 or Vref/4? Thank you.

**Comment by kliment** [comment]
Hey, thanks for your interest!

The full-scale current (per coil) is defined by the following equation:

I = Vref / (5*RSENSE)

In this design, RSENSE is 0.05ohm, so 5_RSENSE = 0.25Ohm.
Thus, I=Vref/0.25 -> I=Vref_4
This means if your vref voltage is say 0.5V, your full-scale current
will be 2A.

If you build this board with a different sense resistor value, be aware
that Vref is not allowed to exceed 3.5V in any situation. This means
that if you want to use the full 2.5A drive current, the maximum sense
resistor value you can use is 0.28Ohms

**Comment by axjurado** [comment]
Thanks a lot for your quick response.

This helps a lot.
