### ISSUE TITLE
.brd file broken

### ISSUE THREAD

**Issue by DuzaBF** [kliment/cooldrv#2]
It seems that .brd file is broken. I was unable to open it in Altium viewer and other viewers

**Comment by kliment** [comment]
I don't know or care much about Altium, and I've never touched Altium in my life, I'm not sure why you expect Altium to be able to read another CAD's format. This was an Eagle project from back when Eagle existed. For what it's worth, Kicad's importer can read it just fine.

**Comment by kliment** [comment]
I added the converted kicad files to the repo as well as the production files (gerber, assembly files, and board images). I hope this helps. I am neither able nor willing to support altium users. Please use Kicad!
